### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by DonalDuck004** [DonalDuck004/ITTVT_Pacman_2023#1]
- [x] Change life display system from images to counters
- [x] Use Page instead of tab items 
- [x] DLL for update from git -- working in progress
- [ ] .bat file to build wizard setups using winrar
- [x] Try to open project on another machine
- [ ] Investigate on a compilation error that occurs 1 out of 2
- [ ] Investigate on game freezes 
- [x] Cyan and Orange ghost are swapped in world builder program
